### ISSUE TITLE
Не працює зходу

### ISSUE THREAD

**Issue by danbst** [EarlGray/COSEC#1]
Видає наступне (запускаю через бохс, з  дискетки):

```
                    <<<<< Welcome to COSEC >>>>>
```

freeing   pages from 0 to 9E; n_pages = 9F
reserving pages from 9F to 9F;
reserving pages from E8 to FF;
freeing   pages from 100 to 1FEF; n_pages = 1FF0
reserving pages from 100 to 10F;
Allocating 101 pages at [4DD]
theHeap at *4DD000
mount('rootfs', '/', 'ramfs')
TODO: vfs_mkdir('/etc')
TODO: vfs_mkdir('/dev')
mount('devfs', '/dev', 'ramfs')
TODO: not root pathname resolution
error: 0x8002

**Comment by EarlGray** [comment]
Це нормальна поведінка, далі має бути запрошення ( |< ) із курсором.

**Comment by danbst** [comment]
немає запрошення, система не реагує на клаву

**Comment by EarlGray** [comment]
bochs 2.4.6 на 64-бітній машині — клавіатура працює. Яка версія Бохса? Можна ще якісь деталі? 
Можна обірвати виконання Бохса (Ctrl-C) і скинути стан віртуальної машини сюди (має показатись у консолі) + id коміта?

**Comment by danbst** [comment]
bochs, 64-bit

При старті запускається груб. Ввожу

 kernel (fd0)/kernel
 boot

Вивалюється повідомлення з топік посту. Клава не працює. Можливо неправильно компілював?

**Comment by danbst** [comment]
Ага, конфіг бохса

```
floppya: 1_44= /storage/dev/COSEC/cosec.img, status=inserted
romimage: file=/usr/share/bochs/BIOS-bochs-latest
megs: 32
boot: floppy
vga_update_interval: 50000
keyboard_serial_delay: 250
cpu: count=1, ips=500000
mouse: enabled=0
private_colormap: enabled=0
i440fxsupport: enabled=0
clock: time0=0
log: -
panic: action=ask
error: action=report
info: action=report
debug: action=ignore

```

**Comment by EarlGray** [comment]
Правильна послідовність завантаження в GRUB:
  kernel (fd0)/kernel
  multiboot
або
  kernel --type=multiboot (fd0)/kernel
  boot
Все-таки це не зовсім лінукс)

**Comment by danbst** [comment]
неа, проблема не у цьому. В такому разі я взагалі нічого би не побачив.

Знайшов рядок, на якому зависає:

```
#define i386_intrs_enable()  asm ("\t sti \n")
```

**Comment by EarlGray** [comment]
Прошу скинути лог Бохса.

**Comment by danbst** [comment]
http://paste2.org/p/1818687

**Comment by danbst** [comment]
через qemu, до-речі, працює.

**Comment by danbst** [comment]
unable to reproduce

**Comment by EarlGray** [comment]
If you sit near your bugtracker long enough, you will see your bugs passing by closed :)
